### ISSUE TITLE
How to tune each rollout and how to use the Pareto-based EA

### ISSUE THREAD

**Issue by LiuJia68** [walkerning/aw_nas#54]
Hi, I tried to set: "inner_controller_type: pareto-evo" and "evaluator_type: tune" for robust predictor-based search. But it seems multishot-robnas does not support these. Could you elaborate how to tune each rollout and how to use the Pareto-based EA? Thank you so much.

**Comment by A-LinCui** [comment]
- **Evaluator:** Currently，evaluator "tune" doesn't support evaluation for robust search.
- **Controller:** We test the pareto-based EA for robust search. All works well. Errors may result from mistakes in the configuration file. The example configurations of the controller and objective for reference are as follows.
  - **controller**
  ```
  controller_type: pareto-evo
  controller_cfg:
      # Schedulable attributes:
     mode: eval
     rollout_type: dense_rob
     init_population_size: 100
     eval_sample_strategy: all
     avoid_repeat: true
     avoid_mutate_repeat: true
     num_eliminate: 10
     perf_names: ["acc_clean", "acc_adv", "flops"]
  ```
  - **objective**
  ```
  ## ---- Component objective ----
  objective_type: adversarial_robustness_flops
  objective_cfg:
     # Schedulable attributes:
     epsilon: 0.03137254901960784
     n_step: 7
     step_size: 0.00784313725490196
     mean: [0.49139968, 0.48215827, 0.44653124]
     std: [0.24703233, 0.24348505, 0.26158768]
     rand_init: true
     adv_loss_coeff: 0.5
     as_controller_regularization: false
     as_evaluator_regularization: true
     adv_reward_coeff: 0.5
     schedule_cfg: null
  ## ---- End Component objective ----
  ```
